//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace irovagoWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agency
    {
        public Agency()
        {
            this.Logins = new HashSet<Login>();
            this.Offers = new HashSet<Offer>();
        }
    
        public int agencyID { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string brand { get; set; }
    
        public virtual ICollection<Login> Logins { get; set; }
        public virtual ICollection<Offer> Offers { get; set; }
    }
}
