//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace irovagoWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Logins = new HashSet<Login>();
            this.FavoriteOffers = new HashSet<FavoriteOffer>();
        }
    
        public int customerID { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string address { get; set; }
    
        public virtual ICollection<Login> Logins { get; set; }
        public virtual ICollection<FavoriteOffer> FavoriteOffers { get; set; }
    }
}
