//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace irovagoWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FavoriteOffer
    {
        public int favoriteOfferID { get; set; }
        public Nullable<int> customerID { get; set; }
        public Nullable<int> offerID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Offer Offer { get; set; }
    }
}
