//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace irovagoWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public Hotel()
        {
            this.Offers = new HashSet<Offer>();
            this.HotelRoomTypes = new HashSet<HotelRoomType>();
        }
    
        public int hotelID { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string url { get; set; }
        public string explanation { get; set; }
        public string imgHotel { get; set; }
    
        public virtual ICollection<Offer> Offers { get; set; }
        public virtual ICollection<HotelRoomType> HotelRoomTypes { get; set; }
    }
}
