//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace irovagoWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int loginID { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<int> customerID { get; set; }
        public Nullable<int> agencyID { get; set; }
        public Nullable<int> adminID { get; set; }
    
        public virtual Agency Agency { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Admin Admin { get; set; }
    }
}
