//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace irovagoWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomType
    {
        public RoomType()
        {
            this.HotelRoomTypes = new HashSet<HotelRoomType>();
            this.Offers = new HashSet<Offer>();
        }
    
        public int roomTypeID { get; set; }
        public string name { get; set; }
        public string type { get; set; }
    
        public virtual ICollection<HotelRoomType> HotelRoomTypes { get; set; }
        public virtual ICollection<Offer> Offers { get; set; }
    }
}
